server:
  port: 8082

dubbo:
  application:
    name: demo-provider

  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
    
  protocol:
     name: dubbo
     port: 20880

  monitor:
     protocol: registry

  configcenter: zookeeper://127.0.0.1:2181

#  metrics:
#     port: 20880
#     protocol: dubbo
#  provider:
#    filter: metrics

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.sweet.common.model
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookk?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
#    druid:
#      initial-size: 3
#      max-active: 30
